export const ALLOWED_PRODUCTS: readonly string[] = `
NIVELADOR
PINÇA DE ENTRADA INFERIOR LB436
FERRAMENTAL SB1338
PINÇA DE SAÍDA
SUPORTE PINÇA ENTRADA
ABA SUPORTE DA TELA
ARRUELA
PORCA DO BRAÇO FIXO
MANIFOLD LUBRIF. AUTOM. BLANK
TRILHO
CUBO DA ENGRENAGEM
ENGREN. 56 D. PLACA CONTROLE REMOTO
BUCHA
ENGRENAGEM (HF  -00002-0168)
ENGRANAGEM (HF  -00002-159A)
ENGRENAGEM (HF  -00002-0179)
PINHAO
ARRUELA ESPECIAL LATERAL
EIXO E PISTAO
MANIFOLD ELÉT. CONVEYOR P/ CIMA 8 SEÇ. L.E.
POLIA DE ALUMINIO 6
EIXO DA EMBREAGEM
CILINDRO DO INVERT
PINÇA ENTRADA
ENGRENAGEM 20 DENTES
TAMPA DA CAIXA FEEDER 360º / MECHANISM BOX COVER
EXCÊNTRICO MEC. BAFFLE
CILINDRO
GARRA ENTRADA INFERIOR
EIXO
BUCHA LONGA INVERT
HASTE MECAN. INJETOR
FLANGE
PANELA SG 7"
PANELA
BRAÇO EXCÊNTRICO TESOURA
BLOCO DE AJUSTE
SUPORTE DE TELA
ENGRENAGEM (HF  -00002-161A)
SUPORTE DO MOTOR REDUTOR
SUPORTE DA PINÇA
SUPORTE DA BORRACHA
MANIFOLD AR PILOTO VÁLV. EVENTOS SUPERIORES 4 SEÇ.
FRENTE DO ALIMENTADOR  (HF-461)
SUPORTE LADO ESQUERDO
MANÍPULO ESPECIAL P/ REGULAGEM SENSOR VERTECH
PLACA DE DESGASTE
BASE DA GUIA
CULOTE
CAIXA (HF  -00002-152A)
MANIFOLD P/ LUBRIFICAÇÃO AUTOMATICA
ESTRUTURA L.D. P/ 8 SEÇ.
PROTEÇÃO FEEDER COLOR
CANTONEIRA DE FIXAÇAO
PISTÃO PLUNGER DG
COLUNA
BRAÇO SUPERIOR
MANCAL
TAMPA
PLACA DE GRAFITE
ARRUELA  (OIS-16-245)
CORPO
FRAME ESTEIRA 4 SEÇ
ROLETE DO CARRO HORIZONTAL
BLOCO LUBRF. LATERAL COLUNA
PLACA SUPORTE P/ GRAFITE
SUPORTE ROLETE
GUARD
GUIA GOTAS ESTR.DIR.
PRESILHA
PINO
SUPORTE DETECTOR PROXIMIDADE
ROLETE TENSOR
ESPAÇADOR
MANIFOLD
POSICIONADOR
EIXO DE REGULAGEM
EIXO ESPECIAL
QUEIMADOR DE 100 MM
BRAÇO DE MOLDE
ESTRUTURA CARRINHO FIRE POLISH
HASTE ROSCADA
SUPORTE DE REGULAGEM
PISTAO SEMI-ACABADO
CHAPA BASE SIMP. L.E
ARRUELA CORRETORA L.I.
SUPORTE L.D.
BLOCO DE CONEXAO DIR.
BRAÇO E TAMPA DE INJETOR S.G. RESFRIAM. GARRAFA ALTA
BUCHA SUPERIOR
TAMPA TRASEIRA
ESCALA
MANIFOLD PILOTO CAIXA DE VÁLV. 4 SEÇ (EM CIMA CONTRA SOPRO)
BASE DO MOTO REDUTOR
CASTANHA
BRAÇO MOLDE 4.5/8 LE
ENGRENAGEM 36 D.
PINO DE GUIA
PLACA TRANSFERÊNCIA RECOZIMENTO P/ IN-LINE MÁQ. A5
PLACA DE TRANFERÊNCIA
MANIFOLD LUBRIF BLANK 4 SEÇ
ROLETE DE TRAÇÃO
ROLETE DE TRAÇÃO ENFARDADEIRA
PROTECAO
SUPORTE MANCAL COMPENSADOR DO BAFFLE
MOLA
ENGR.CONICA 80 D.
BLOCO DUPLO SEÇ.4
DECORAÇÃO
CHAVETA DA BUCHA DO EIXO TRAÇÃO
CHAVETA 2 DO EIXO TRAÇÃO
MANIFOLD DE COMANDO 6 SEÇ.
MANIFOLD P/ AR PILOTO VVM-780 8 SEÇ
MANIFOLD P/ AR PILOTO VVM-780 6 SEÇ
FUNNEL HOLDER
BLOCO DE CONEXAO
ARRUELA ESPECIAL
PORCA DE FIXAÇAO
TAMPA DIANTEIRA
PISTÃO PLUNGER (TESTE)
PONTEIRA (fundo)
GARRA SUPERIOR ENTRADA
BANCADA DE MOLDE
SUPORTE ANTIFLETOR BLANK (CHIFRE)
BLOCO LUBRIF. C/ BASE P/ PINÇA
PROJ 3015 / MÁQ. IS FORNO B - 2023
HASTE DE GUIA
REDUÇÃO 2" X 1"
GUIA DE FUNIL
PARAF. ESPECIAL
CAMISA CARTUCHO AMORT. INF. PINÇA
BLOCO DE CONEXÕES - MÁQUINA A6
CAMISA CARTUCHO AMORT. SUP. INVERT
CHAVETA
SUPORTE DAS VALVULAS - PROTECAO
CANTONEIRA MOLDE / INJETOR VVM-738
VIGA
SUPORTE DO MANCAL
BRAÇO DE INJETOR 7"
BRAÇO DE INJETOR C/ TAMPA
TUBO DE AJUSTAGEM
BOTINHA COM BUCHAS
CONJ. PINO 40
ESPAÇADOR DE BARRAMENTO
PINO ESPECIAL
SUPORTE DA GARRA
PORCA BORBOLETA
CILINDRO DO BAFFLE
CILINDRO DO FUNIL
SUPORTE DO BLOCO MANIFOLD
PLACA P/ BASE DE VALVULA
PROJ 30XX / COMPONENTES FORNO D - 2024
MANIFOLD ELÉTRICO COMANDO ELTERÔNICO 4 SEÇ
PLACA PARA BASE DE VALVULA
SUPORTE E PINO POSICIONADOR
CHAPA
SUPORTE DA CAIXA DE PROTEÇÃO
CANTONEIRA DE AMARAÇÃO
ADAPTADOR
PINÇA
AGULHA
CHAVETA ENGRENAGEM
PLACA 4 ESTEIRA 8 SEÇ
PLACA 3 ESTEIRA 8 SEÇ
PLACA 2 ESTEIRA 8 SEÇ
PLACA 5 ESTEIRA 8 SEÇ
EXTENSÃO DA ESTEIRA END UNIT
BRAÇO DE MOLDE R.H. e L.H.
PINÇA ENTRADA ESQ.
PINÇA SAIDA DIR.
PINÇA SAIDA ESQ.
BEDAME INTERNO 5 mm
PLACA BÁSICA DE DISTRIBUIÇÃO CONVERSÃO D.G. P/ S.G.
BRAÇO DE INJETOR 7" S.G. C/ CONTROLE AR ASSOPRO
CHAPA FIXAÇÃO TOMADA
MANIVELA
PANELA RASA DE 7
PROTEÇÃO DA ESTEIRA
PROTEÇÃO ROLETE SEÇÃO ESTICAGEM
CHAPA DE TRANSFERÊNCIA
CHAPA DESGASTE
PINÇA SAÍDA LB535
MANIFOLD P/ SEÇÃO MODULAR
CAIXA EXC. DA ENGR.
BRAÇO DE MOLDE TIPO TALL BOY
BASE VENT. INTERMIT. DUPLA P/ GR4
DET. PASSAGEM DA VENT. AXIAL DE MOLDE P/ MB-1479
LAMINA TESOURA SIMP.
BRAÇO DE MOLDE NR.6
PALHETA DA PINÇA SB1750
MECANISMO DO BAFFLE
MECANISMO DO INJETOR SG DG 4.1/4"
MECANISMO DE MACHO S.G.4.1/4
SUPORTE TABLET
PINÇA CENTRALIZADORA SB1750
MÓDULO DE CONTROLE FIREPOLISH
CONTATOR DE ENTRADA SB1750
PINÇA ENTRADA SB1750
SUPORTE PINÇA ENTRADA SB1750
SUPORTE PINÇA SAÍDA SB1750
ROLETE E TAMPA SOLDADA
CONTATOR SAÍDA SB1750
PINÇA SAÍDA SB1750
GARRA DE SAÍDA MB1368
REFORÇO FRONTAL
EXCÊNTRICO BAFFLE PISTA MAIOR
EIXO ROLETE 105. 7/8"
PRENSA CABO DO SENSOR CONECTOR M12
SUPORTE PRENSA
PINO DO ROLETE
CABO DA ALAVANCA
DISCO DE PROT. BI PARTIDO
TENSOR
MÁQ. IS 4 SEÇ / LE / C6 / 2023 (PROJ 3020)
SECÇÃO CURVA 65° - R42"
MACANETA
BLOCO SEXTAVADO
GUIA DE GOTA 3.1/2
BLOCO DE CONEXAO ESQ.
BODY HOLDER
BRAÇO DE MOLDE R.H.
BRAÇO DE MOLDE L.H.
BLOCO DE MOLDE TRIPARTIDO
SUPORTE SUPERIOR DA TESOURA LE
SUPORTE DISPOSITIVO DE FRASCOS
CONTATOR INFERIOR LB539
CULOTE LB539
CLICHET LB572
TRAVA AGITADOR
BRAÇO DE INVERSAO TRIPLO
INFRA ESTRUTURA DAS FORNECEDORAS (REFRAX)
EIXO  (RPL)
MACHO DO CORPO DMP-0011-11
CAVIDADE SUPERIOR
PLACA BASE SUPERIOR
PLACA P1
PLACA P2
PLACA SUPORTE
BASE INFERIOR
SUPORTE MEC. DELIVERY MULTI-SCOOP (ANTIGO)
GARRA ENTRADA LB453
PLACA FIXAÇÃO CHUDA
SUPORTE DO ESTRIANTE
SEPARADOR DA BARRA
ESPAÇADOR BARRAMENTO
EIXO SEMI-TERM. INVERT
BALANCIN
BUCHA DO MANCAL
GARRA INFERIOR ENT LB535
SUPORTE
HASTE DE FIXAÇÃO
CAMISA CARTUCHO AMORT. INF. INVERT
PLACA LATERAL
DEFLECTOR 5/8" SEÇ 1-8 INFERIOR
BERÇO MB1544
CULOTE SB1742
CULOTE LB492
SUPORTE ANFORA LB557
GARRA SAIDA MB1261
CULOTE PUCK LB582
CULOTE SB1659
CULOTE MB1118
CULOTE MB1508
CULOTE LB443
PINÇA ENTRADA DIR. MB1375
ACOPLAMENTO L.E
CONTATOR ENTRADA LB500
EIXO ROSCADO DE AJUSTE DO SUPORTE
MANIPULO
SUPORTE AJUSTAVEL
ANEL NYLON P/ CONEXÕES
CHAVE DE REGULAGEM
CULOTE MB1588
CILINDRO INJETOR ANTIGO VVM-108
PONTEIRA
PISTÃO PLUNGER S.G.
PONTEIRA 90
PONTEIRA 82
PONTEIRA 56
PPONTEIRA 60
PONTEIRA 64
PONTEIRA 76
ROLETE 31
ROLETE 39
ROLETE 43
CARRO TRANSPORTADOR AMOSTRA
PINÇA SAÍDA ESQ MB1118
STOP MB1537
PINÇA SAIDA MB1537
ELETRODO OMBRO DO MOLDE MACHO E FÊMEA MB1594
CORPO DA GARRA DIREITA
GARRA PUXADOR C/ VENTURI | QG | ESQ-DIR
GARRA PUXADOR C/ VENTURI | TG | ESP 10. 1/2"
TOPO BERÇO PINTURA INTERNA MB1579
CONTATOR SAIDA INFERIOR MB1162
MEC. SCOOP C/ CHAPA
BUCHA FRONTAL
BERÇO
PINÇA ESQ. MB1527
TRAVA
TRILHOS E SUPORTE
GARRA SAIDA
BRAÇO DE MOLDE C/ PORTA MOLDE Ø 3" | TG
BRACO DE INJETOR DG
GARRA ENTRADA
PINÇA SUPERIOR LB536
GARRA 50 DIR. TRANSF. C/ CORDÃO INOX
STOP MB1410
UNIÃO
ELO
PORTA MOLDE  Ø 3" | TG
SUPORTE DAS MOLAS ADAPT. CHUDA QG
PORTA GUIA DE GOTA
LINGUETA
HASTE 7"
ESPAÇADOR DUPLO 2" FURO Ø 1/8"
BUCHA ROSCADA
BANCADA DE INVERSAO
BRAÇO MOLDE SIMPLES NR.3
CONTROLE DE GUIA DE GOTA Q.G. (CHUDA)
BASE DO AJUSTADOR
DEFLECTOR Ø 1.7/8" SG / SEÇ 3 E 6
PISTA INFERIOR
ENGRENAGEM 45Z
GARRA À DIREITA C/ GRAFITE
BRAÇO DE INVERSAO
BRAÇO DE NECK/INVERSÃO | TG
PLACA
BUCHA DA HASTE DE AJUSTE
ARRUELA DA ARTICULAÇÃO
PINO TRAVA
PINO DA MOLA
PARAFUSO DE REGULAGEM
HASTE 10"
HASTE 9"
HASTE 8"
PINO TRAVA CHUDA
PINO DE ARTICULAÇÃO
SUPORTE GUIA DE GOTA
FIXADOR DA LAMINA
ARRUELA CORRETORA 220
ARRUELA CORRETORA 210
SUPORTE PINÇA ENTRADA LB536
BLOCO DA CAMERA
CHAPA DE APOIO
PROTEÇÃO
CLICHET MB1413
BRAÇO DISPOSITIVO QUEDA ENERGIA
BICA DUPLA NR.2 SUP.
BICA DUPLA NR.2 SUP. SEÇ.3
BICA DUPLA NR.2 SUP. SEÇ.5
BICA DUPLA NR.2 INF.
CALHA ELÉTRICA CHUDA
EIXO COM SUPORTE
SUPORTE E BUCHAS
PROTEÇÃO LATERAL
PROTEÇÃO LATERAL TRILHO
SUPORTE PAINEL ELÉTRICO
CALHA DE CABOS
APOIO CALHA ELÉTRICA
TAMPA CALHA ELÉTRICA CHUDA
CULOTE MB1546
GARRA SAIDA INFERIOR MB1525
ROLETE
ROLETE DE GUIA
SUPORTE DE GARRA DO TRANSFERIDOR
GARRA DE SAÍDA MB1319
BRAÇO DE INVERSÃO NECK | DG
DEFLETOR 1 SUP. SEÇ. 2 A 5
CALHA PORTA ESTEIRA DUPLA
CALHA PORTA ESTEIRA
PLACA DE CONTENÇÃO | BANDEIRINHA
Selo | 30,9mmC | R-186
BICA NR. 2 SEÇ.1 A 6
BRAÇO DE MOLDE DG
REFRIG INTERMITENTE DUPLA
CARTUCHO AMORT. SUP.
FLANGE ACOPLAMENTO REDUTOR CNC K350
TAMPA CAIXA DE FEEDER ANTIGA
CAIXA C/ TAMPA 144-14022
PORCA ROSCA NC
FUNIL DE GUIA
SOQUETE
SUPORTE PINÇA ENTRADA MB1546
PISTAO
PINÇA SAIDA DIR. LB493
PINÇA ENTRADA ESQ. LB493
PINÇA ENTRADA DIR.LB493
PINÇA SAIDA ESQ.LB493
BANCADA SOLTA PINO
EIXO DO ROLO
BERÇO DE TOPO MB1578
VAL PARADA MOLDE E INJETOR
BASE
CILINDRO DO INJETOR
BASE AJUSTAVEL VERTICAL
CAPA ACELERADOR
BRAÇO DE FUNIL Nº1 | SG
MANIFOLD BOTOEIRA PRENSA
EIXO SEM FIM
BRAÇO DE INJETOR
STOP DO EIXO SEM FIM
ABRAÇADEIRA
BRAÇADEIRA
STOP MB1508
ENCOSTO
PINO ARTICULAÇAO
ARRUELA FINA DO TAMBOR
SUPORTE DE GIRO
EIXO ROSCADO CHUDA
HASTE DE SUSTENTAÇÃO
SUPORTE DO FUNIL CHUDA
BASE DE AJUSTE
BASE DO SUPORTE CHUDA
ENGRENAGEM SEGMENTAR
EIXO GUIA PRENSA
FUNIL GRAFITE CHUDA
GUIA INTERNA P/ TRANSFERIDOR
CONTATOR ENTRADA LB502
CONTATOR ENTRADA SB1764
CONTATOR SUPERIOR SB1764
BERÇO COMPLETO TAMPOGRAFICO 2 LB471
BERÇO COMPLETO TAMPOGRAFICO 2 MB1393
SUPORTE DO ORIFICIO
POSTE GUIA
TOPE
GARRA 50X60 DIR TRANSF CHUDA
PLACA DE GRAFITE COM REBAIXO
MOLD INSERT LINK
GARRA SUPERIOR SB1776
APALPADOR
GUIA
PLUG DE MESA MB-1601
BRAÇO INVERSAO DUPLO
CILINDRO PINÇA
BRAÇO E TAMPA BAFFLE SG
PINÇA INFERIOR MB1477
HASTE COM ROSCA
GARRA SAIDA LB594
CONTATOR SUPERIOR MB1593
SUPORTE PRATO MORTO
COPINHO
CONJ. MEC. SCOOP
PLACA FRONT FEEDER C8 CHUDA
TAMPA DO RONDELE
TRAVA DO SUPORTE
FUSIVEL INJETOR CHUDA
GARRA 50 X 60 SQ. TRANSF. CHUDA
CAMISA DO MANCAL DO AGITADOR
ENGR. 48 D. 1.1/2
COLUNA DIR.
PLACA DE TRANSFERENCIA
SUPORTE DE MACHO
CONTATOR INFERIOR MB1579
CONTATOR SUPERIOR MB1579
CONTATOR INTERMEDIÁRIO MB1579
PISTA INFERIOR PARA TUBO 7
EIXO DO PINO ENG.
BUCHA PINO ENGREN
ENGREN DO PINO
PINO ENG.
MONTAGEM PINO ENGRENAGEM
CONJUNTO PINO ENGRENADO P15
CONJ. PINO ENGRENADO
CONTROLE REMOTO
PORTA MACHO SG Ø 3. 1/8"
POLIA DENTADA 36 D.
BLOCO 3/4
PORTA TUBO SUPERIOR 7
FLAP
BASE SUPERIOR
CILINDRO SUPERIOR
CILINRO INFERIOR
`
  .trim()
  .split(/\r?\n/);
